
from django.urls import path,include
from . import views
urlpatterns = [
    path('',views.index,name="home"),
    path('product',views.product_home,name="product"),
    path("News_Feed",views.news_feed,name="news_feed"),
    path("News_Feed/<int:post_id>",views.news_post,name='news_post'),
    path("About_us",views.about_us,name="about_us"),
    path("contact_us",views.contact_us,name = "contact_us"),
    path("query_form",views.query_form,name="query_form"),
    path("import_data",views.import_data),
    path('dye_and_intermediates',views.intermediated,name="dye_and_intermediates"),
    path('Food_and_pharma',views.Food_pharma,name="Food_and_pharma"),
    path('shades_and_pigments',views.shades_and_pigments,name="shades_and_pigments"),
    path('varieties_and_cosmetics',views.varieties_and_cosmetics,name="varieties_and_cosmetics"),
    path('intermediates_list',views.intermediates_desc,name="intermediates_desc"),
    path('acid_dyes_list',views.acid_dyes_list,name="acid_dyes"),
    path('basic_dyes',views.basic_dyes,name="basic_dyes"),
    path('basic_dyes/<str:prod_name>',views.basic_dyes_sub,name="basic_dyes_sub"),
    path('direct_dyes_list',views.direct_dyes_list,name="direct_dyes"),
    path('food_lake_sub',views.food_lake_color_list,name="food_lake_color"),
    path('solvent_dyes_list',views.solvent_dyes_list,name="solvent_dyes"),
    path('reactive_dyes_sub',views.reactive_me_dyes_list,name="reactive_me_dyes"),
    path('reactive_dyes_sub/<str:prod_name>',views.reactive_dyes_sub,name = "reactive_dyes_sub"),
    path("D_C_",views.D_C_color,name="D_C_color"),
    path("lake_color",views.Lake_color,name="lake_color"),
    path("ess_oil_list",views.ess_oil_list,name="esse_oil_list"),
    path("ess_oil_list/<str:oil_name>",views.ess_basic_oil,name="esse_oil_list_sub"),
    path("oleoresin_oil",views.oleoresin_oil,name="oleoresin_oil"),
    path("natural_flower_oil",views.natural_flower_oil,name="natural_flower_oil"),
    path("Food_and_pharma/<str:prod_name>",views.food_pharma_sub,name = "food_and_pharma_sub"),
    #path("Food_and_pharma/<str:prod_name>/<str:prod_name_sub>",views.food_pharma_sub_prod,name = "food_and_pharma_sub"),
    path("shades_and_pigment/<str:prod_name>",views.shades_and_pigments_sub,name = "shades_and_pigments_sub"),
    path("acid_dyes",views.acid_dyes_sub,name="acid_dyes_sub"),
    path("acid_dyes/<str:prod_name>",views.acid_dyes_sub_tables,name="acid_dyes_sub_tables"),
    path("food_lake_sub/<str:prod_name>",views.food_lake_sub,name="food_lake_sub"),
    path("Search",views.search_filter,name="search_filter"),
    path("Free_sample",views.free_sample,name="free_sample"),
    path("colors",views.color_set)
]