# Generated by Django 3.1.5 on 2021-01-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_acid_dyes_basic_dyes_direct_dyes_food_and_lake_reactive_dyes_solvet_dyes'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_C_color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CI_no', models.IntegerField()),
                ('D_C_no', models.CharField(max_length=100)),
                ('CI_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='essential_oil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('oil_type', models.CharField(choices=[('ant_bac', 'Anti Bacterial Oil'), ('anti_', 'antiviral Oil'), ('carrier', 'carrier Oil'), ('C_B', 'Clay & Butter Oil'), ('Frag', 'Fragrance Oil'), ('herb', 'Herbal Oil'), ('N_E', 'Natural Essential Oil'), ('N_i', 'Nature Odentical Oils'), ('org_cold_press', 'Organic Cold Pressed Oils')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='lake_color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('color_index_no', models.IntegerField()),
                ('EEC_no', models.CharField(max_length=10)),
                ('CASE_no', models.CharField(max_length=100)),
                ('Other_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='natural_flower_oil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('case_no', models.CharField(max_length=100)),
                ('botonic_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='oleoresin_oil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('case_no', models.CharField(max_length=100)),
                ('botonic_name', models.CharField(max_length=100)),
            ],
        ),
    ]
