# Generated by Django 3.1.5 on 2021-01-23 14:50

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_d_c_color_essential_oil_lake_color_natural_flower_oil_oleoresin_oil'),
    ]

    operations = [
        migrations.CreateModel(
            name='news_feed_POST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('Event_Brief', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to="news_feed")),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.news_feed_post')),
            ],
        ),
    ]
