# Generated by Django 3.1.5 on 2021-01-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210123_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_images',
            name='image_title',
            field=models.CharField(default='', max_length=150),
        ),
    ]
