# Generated by Django 3.1.5 on 2021-01-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_post_images_image_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=100)),
                ('User_Email', models.EmailField(max_length=254)),
                ('User_mobile', models.CharField(max_length=15)),
                ('User_Query', models.TextField()),
            ],
        ),
    ]
