# Generated by Django 3.1.5 on 2021-01-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210124_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='veterinary_apis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_api', models.CharField(max_length=100)),
                ('Case_no', models.CharField(max_length=40)),
                ('Therapeutic_Segments', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='intermediates',
            options={'ordering': ('product_name', 'compound', 'case_no')},
        ),
    ]
