# Generated by Django 3.1.5 on 2021-01-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210125_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='amino_acid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('Case_no', models.CharField(max_length=50)),
                ('strength', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='combination_formulations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='companion_animal_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('presentation', models.CharField(max_length=50)),
                ('dosage_form', models.CharField(max_length=100)),
                ('therapeutic_segments', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='injectables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='livestock_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('presentation', models.CharField(max_length=50)),
                ('dosage_form', models.CharField(max_length=100)),
                ('therapeutic_segments', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='medical_supply_equip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Minerals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('Case_no', models.CharField(max_length=50)),
                ('strength', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='nasal_drop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='oral_suspensions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='other_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('presentation', models.CharField(max_length=50)),
                ('dosage_form', models.CharField(max_length=100)),
                ('therapeutic_segments', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='patented_impurity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impurity_name', models.CharField(max_length=100)),
                ('Case_no', models.CharField(max_length=50)),
                ('Product_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pellet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_api', models.CharField(max_length=100)),
                ('Case_no', models.CharField(max_length=40)),
                ('Therapeutic_Segments', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='poultry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('presentation', models.CharField(max_length=50)),
                ('dosage_form', models.CharField(max_length=100)),
                ('therapeutic_segments', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ref_std_impurities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impurity_name', models.CharField(max_length=100)),
                ('Case_no', models.CharField(max_length=50)),
                ('Product_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Specialities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('Case_no', models.CharField(max_length=50)),
                ('strength', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stabilized_vitamins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('Case_no', models.CharField(max_length=50)),
                ('strength', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tablet_capsules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=100)),
            ],
        ),
    ]
