# Generated by Django 3.1.5 on 2021-01-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_amino_acid_combination_formulations_companion_animal_product_injectables_livestock_product_medical_s'),
    ]

    operations = [
        migrations.CreateModel(
            name='flouroscent_pigments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='shades_and_pigment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('case_no', models.CharField(max_length=15)),
                ('type', models.CharField(choices=[('waterbase_intjet_ink', 'Waterbase inkjet Int'), ('universal_stainer', 'Universal Stainer'), ('paints', 'paints'), ('machine_cotaing_colorant', 'Machine Cotaing Colorant'), ('inorganic_pigment', 'Inorganic Pigment'), ('industrial_coating', 'Industrial Coating'), ('cement_architecture_dispersion', 'Cement Architecture Dispersion'), ('architecture_paint', 'Architecture Paints'), ('13_waterbase_flexo_ink', '13 Waterbase Flexo ink'), ('11_mixed_meta_oxides', '11 Mixed Meta Oxides'), ('08_12_pvc_masterbatches', '08 + 12 Pvc and Pvc Master Batches'), ('toner_fanal_pigment', 'Toner Fanal Pigments'), ('hign_performance_pigment', 'High Performance Pigments')], max_length=50)),
            ],
        ),
    ]
