# Generated by Django 3.1.5 on 2021-01-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_about_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essential_oil',
            name='oil_type',
            field=models.CharField(choices=[('ant_bac', 'Anti Bacterial Oil'), ('anti_', 'antiviral Oil'), ('carrier', 'carrier Oil'), ('C_B', 'Clay & Butter Oil'), ('Frag', 'Fragrance Oil'), ('herb', 'Herbal Oil'), ('N_E', 'Natural Essential Oil'), ('N_i', 'Nature Identical Oils'), ('org_cold_press', 'Organic Cold Pressed Oils'), ('org_ess_oil', 'Organic Essential Oil')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lake_color',
            name='color_index_no',
            field=models.CharField(max_length=50),
        ),
    ]
