# Generated by Django 3.1.5 on 2021-01-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210126_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='acid_dyes_sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shade', models.CharField(max_length=100)),
                ('C_I_name', models.CharField(max_length=100)),
                ('case_no', models.CharField(max_length=100)),
                ('Application', models.CharField(max_length=100)),
                ('wool', models.BooleanField(default=False)),
                ('Polyamide', models.BooleanField(default=False)),
                ('Wood_Stain', models.BooleanField(default=False)),
                ('Leather', models.BooleanField(default=False)),
                ('Cotton', models.BooleanField(default=False)),
                ('Paper', models.BooleanField(default=False)),
                ('Alluminium_Anodize', models.BooleanField(default=False)),
                ('SILK', models.BooleanField(default=False)),
                ('INK', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='leveling_dyes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shade', models.CharField(max_length=100)),
                ('C_I_name', models.CharField(max_length=100)),
                ('case_no', models.CharField(max_length=100)),
                ('Application', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='mill_dyes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shade', models.CharField(max_length=100)),
                ('C_I_name', models.CharField(max_length=100)),
                ('case_no', models.CharField(max_length=100)),
                ('Application', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='acid_dyes',
        ),
    ]
