# Generated by Django 3.1.5 on 2021-01-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210126_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='metal_complex_dyes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shade', models.CharField(max_length=100)),
                ('C_I_name', models.CharField(max_length=100)),
                ('case_no', models.CharField(max_length=100)),
                ('Application', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('1_1_metal_complex_dyes', '1 1 METAL COMPLEX DYES'), ('1_2_metal_complex_dyes', '1 2 METAL COMPLEX DYES')], max_length=50)),
            ],
        ),
    ]
