# Generated by Django 3.1.5 on 2021-01-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_metal_complex_dyes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acid_dyes_sub',
            name='Alluminium_Anodize',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='acid_dyes_sub',
            name='Cotton',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='acid_dyes_sub',
            name='INK',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='acid_dyes_sub',
            name='Leather',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='acid_dyes_sub',
            name='Paper',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='acid_dyes_sub',
            name='Polyamide',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='acid_dyes_sub',
            name='SILK',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='acid_dyes_sub',
            name='Wood_Stain',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='acid_dyes_sub',
            name='wool',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'No')], max_length=5),
        ),
    ]
