# Generated by Django 3.1.5 on 2021-01-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210126_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_dyes',
            name='type',
            field=models.CharField(choices=[('L', 'LIQUID'), ('P', 'POWDER')], default='L', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acid_dyes_sub',
            name='Alluminium_Anodize',
            field=models.CharField(choices=[('-', 'yes'), ('N', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='acid_dyes_sub',
            name='Cotton',
            field=models.CharField(choices=[('Y', 'yes'), ('-', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='acid_dyes_sub',
            name='INK',
            field=models.CharField(choices=[('Y', 'yes'), ('-', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='acid_dyes_sub',
            name='Leather',
            field=models.CharField(choices=[('Y', 'yes'), ('-', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='acid_dyes_sub',
            name='Paper',
            field=models.CharField(choices=[('Y', 'yes'), ('-', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='acid_dyes_sub',
            name='Polyamide',
            field=models.CharField(choices=[('Y', 'yes'), ('-', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='acid_dyes_sub',
            name='SILK',
            field=models.CharField(choices=[('Y', 'yes'), ('-', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='acid_dyes_sub',
            name='Wood_Stain',
            field=models.CharField(choices=[('Y', 'yes'), ('-', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='acid_dyes_sub',
            name='wool',
            field=models.CharField(choices=[('Y', 'yes'), ('-', 'No')], max_length=5),
        ),
    ]
