# Generated by Django 3.1.5 on 2021-01-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20210126_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='blended_color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('case_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FD_c_color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FD_C_color', models.CharField(max_length=100)),
                ('common_name', models.CharField(max_length=100)),
                ('Hue', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='food_color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('ci_no', models.IntegerField()),
                ('FD_C_color', models.CharField(max_length=100)),
                ('CI_refrence', models.CharField(max_length=100)),
                ('EC_no', models.CharField(max_length=100)),
                ('case_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='lake_color_dyes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('ci_no', models.IntegerField()),
                ('FD_C_color', models.CharField(max_length=100)),
                ('CI_refrence', models.CharField(max_length=100)),
                ('EC_no', models.CharField(max_length=100)),
                ('case_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='food_and_lake',
        ),
        migrations.AddField(
            model_name='reactive_dyes',
            name='type',
            field=models.CharField(choices=[('HE_dyes', 'Reactice He Dyes'), ('Hot_dyes', 'Reactice Hot Dyes'), ('ME_dyes', 'Reactice Me Dyes'), ('printing_dyes_1', 'Reactice Printing  Dyes 1'), ('printing_dyes_2', 'Reactice Printing  Dyes 2'), ('vinyl_sulphone_base_dye', 'REACTIVE VINYL SULPHONE BASE DYE')], default='HE_dyes', max_length=50),
            preserve_default=False,
        ),
    ]
