# Generated by Django 3.1.5 on 2021-01-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20210126_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='direct_dyes',
            name='Alluminium_Anodize',
            field=models.CharField(choices=[('Y', 'yes'), ('-', 'No')], default='-', max_length=5),
        ),
        migrations.AddField(
            model_name='direct_dyes',
            name='Ink',
            field=models.CharField(choices=[('Y', 'yes'), ('-', 'No')], default='-', max_length=5),
        ),
        migrations.AddField(
            model_name='direct_dyes',
            name='Leather',
            field=models.CharField(choices=[('Y', 'yes'), ('-', 'No')], default='-', max_length=5),
        ),
        migrations.AddField(
            model_name='direct_dyes',
            name='Paper',
            field=models.CharField(choices=[('Y', 'yes'), ('-', 'No')], default='-', max_length=5),
        ),
        migrations.AddField(
            model_name='direct_dyes',
            name='Polyamide',
            field=models.CharField(choices=[('Y', 'yes'), ('-', 'No')], default='-', max_length=5),
        ),
        migrations.AddField(
            model_name='direct_dyes',
            name='Silk',
            field=models.CharField(choices=[('Y', 'yes'), ('-', 'No')], default='-', max_length=5),
        ),
        migrations.AddField(
            model_name='direct_dyes',
            name='Wood_Stain',
            field=models.CharField(choices=[('Y', 'yes'), ('-', 'No')], default='-', max_length=5),
        ),
        migrations.AddField(
            model_name='direct_dyes',
            name='Wool',
            field=models.CharField(choices=[('Y', 'yes'), ('-', 'No')], default='-', max_length=5),
        ),
        migrations.AddField(
            model_name='direct_dyes',
            name='cotton',
            field=models.CharField(choices=[('Y', 'yes'), ('-', 'No')], default='-', max_length=5),
        ),
        migrations.AddField(
            model_name='direct_dyes',
            name='shade',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
