# Generated by Django 3.1.5 on 2021-01-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20210127_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='lake_color_dyes',
            name='other_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
