# Generated by Django 3.1.5 on 2021-01-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20210127_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_color',
            name='ci_no',
            field=models.CharField(max_length=50),
        ),
    ]
