# Generated by Django 3.1.5 on 2021-01-26 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20210127_0116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lake_color',
        ),
    ]
