# Generated by Django 3.1.5 on 2021-01-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_home_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=10)),
                ('Address_Line_1', models.CharField(max_length=100)),
                ('Address_Line_2', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('customer_care_number', models.IntegerField()),
                ('customer_care_Email_Id', models.EmailField(max_length=254)),
                ('facebook_page', models.CharField(max_length=100)),
                ('whatsup_link', models.CharField(max_length=100)),
                ('we_chat_link', models.CharField(max_length=100)),
            ],
        ),
    ]
