# Generated by Django 3.1.5 on 2021-02-01 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_company_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amino_acid',
            old_name='Case_no',
            new_name='case_no',
        ),
        migrations.RenameField(
            model_name='minerals',
            old_name='Case_no',
            new_name='case_no',
        ),
        migrations.RenameField(
            model_name='patented_impurity',
            old_name='Case_no',
            new_name='case_no',
        ),
        migrations.RenameField(
            model_name='pellet',
            old_name='Case_no',
            new_name='case_no',
        ),
        migrations.RenameField(
            model_name='ref_std_impurities',
            old_name='Case_no',
            new_name='case_no',
        ),
        migrations.RenameField(
            model_name='specialities',
            old_name='Case_no',
            new_name='case_no',
        ),
        migrations.RenameField(
            model_name='stabilized_vitamins',
            old_name='Case_no',
            new_name='case_no',
        ),
        migrations.RenameField(
            model_name='veterinary_apis',
            old_name='Case_no',
            new_name='case_no',
        ),
    ]
