# Generated by Django 3.1.5 on 2021-02-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20210202_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=200)),
                ('email_id', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=13)),
                ('Requirement_file', models.FileField(upload_to='user_requirement/')),
            ],
        ),
    ]
