# Generated by Django 3.1.5 on 2021-02-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_user_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_detail',
            name='sales_department_email_id',
            field=models.EmailField(default='sales@kewinchem.com', max_length=254),
        ),
        migrations.AddField(
            model_name='company_detail',
            name='sales_department_email_id_pass',
            field=models.CharField(default='123', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company_detail',
            name='sales_department_number',
            field=models.IntegerField(default=-1),
        ),
    ]
