# Generated by Django 3.1.5 on 2021-02-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20210207_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='category_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.IntegerField(choices=[[1, 'Dyes & Intermidiates'], [2, 'Food & Pharma'], [3, 'Varieties in Cosmetic'], [4, 'Shades of  pigments']])),
                ('Refrence_image', models.ImageField(upload_to='category/media/')),
            ],
        ),
    ]
