# Generated by Django 3.1.5 on 2021-02-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_category_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_images',
            name='Refrence_image',
            field=models.ImageField(default='default.jpg', upload_to='category/media/'),
        ),
        migrations.AlterField(
            model_name='category_images',
            name='category_type',
            field=models.IntegerField(choices=[[0, 'Default'], [1, 'Dyes & Intermidiates'], [2, 'Food & Pharma'], [3, 'Varieties in Cosmetic'], [4, 'Shades of  pigments']], default=0),
        ),
    ]
